### DISCUSSION TITLE
Does Congo support Google Analytics 4?

### DISCUSSION THREAD

**Discussion by vinceimbat** [jpanther/congo#132] [Q&A] [answered]
Hi,

Just curious. Does Congo support GA4? If so, is it enough to just add the G measurement ID as it is with the UA tracking ID in the config file as instructed here: https://jpanther.github.io/congo/docs/partials/ ?

Thanks!

**Comment by jpanther** [comment, marked as answer]
Yes, it supports both v3 and v4. Either of these will work:

```toml
googleAnalytics = "UA-PROPERTY_ID"
googleAnalytics = "G-MEASUREMENT_ID"
```

I'll add some extra detail to the documentation.
