### DISCUSSION TITLE
Add an optionnal cover for articles

### DISCUSSION THREAD

**Discussion by OxNinja** [jpanther/congo#182] [Ideas]
Add the possibility to use a cover for posts such as:
<img width="348" alt="image" src="https://user-images.githubusercontent.com/57400445/164255935-14806201-5e8e-4c78-bba6-e5cac624d711.png">

Cover which will be displayed in the post itself, code exemple to use a cover in a post:

```yaml
title: My post title
cover:
  image: cover.jpg
```

In the upcoming days I will try to do a PR :pray:
