### DISCUSSION TITLE
Setting TOC depth

### DISCUSSION THREAD

**Discussion by quant-dc** [jpanther/congo#186] [Q&A] [answered]
Hi All,

Quick question related to the fantastic new table of contents feature in the 2.0 release. The [docs](https://jpanther.github.io/congo/docs/version-2/#tables-of-contents) allude to setting the TOC depth at  an article and global level. I've set the configuration in `markup.toml` and it appears to be respected across the site. 

Is there a way to overwrite the global setting on an article by article basis? I have attempted the following front matter but with no luck:

```toml
title = "Example"
...
[markup]
    [markup.tableOfContents]
        endLevel = 1
        startLevel = 1
```

Thanks for the fantastic work and project!

David
