### DISCUSSION TITLE
main.css is not getting generated correctly, and has <alpha-value> throughout

### DISCUSSION THREAD

**Discussion by rshmhrj** [jpanther/congo#369] [Q&A] [answered]
I removed any custom css in my `assets/css` folder -- just kept the `scheme/darkOcean.css`

`package.json` has:
```json
    "scripts": {
        "server": "hugo server -b http://localhost -p 1313",
        "dev": "NODE_ENV=development ./themes/congo/node_modules/tailwindcss/lib/cli.js -c ./themes/congo/tailwind.config.js -i ./themes/congo/assets/css/main.css -o ./assets/css/compiled/main.css --jit -w",
        "build": "NODE_ENV=production ./themes/congo/node_modules/tailwindcss/lib/cli.js -c ./themes/congo/tailwind.config.js -i ./themes/congo/assets/css/main.css -o ./assets/css/compiled/main.css --jit"
    }
```

When I run `npm run build` or `npm run dev`, the `assets/compiled/main.css` has a ton of errors like:

```css
/* LineHighlight */

.chroma .hl {
  margin-left: -1rem;
  margin-right: -1rem;
  display: block;
  width: auto;
  background-color: rgba(var(--color-primary-100), <alpha-value>);
  padding-left: 1rem;
  padding-right: 1rem;
}

.dark .chroma .hl {
  background-color: rgba(var(--color-primary-900), <alpha-value>);
}
```
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/750874/201547601-74aa5682-4ded-41e4-8a9a-d90ec9bad712.png">

It seems the `<alpha-value>` is incorrect somehow, but I don't know what's causing it.  Any ideas?
