### DISCUSSION TITLE
utteranc don't  work

### DISCUSSION THREAD

**Discussion by XdpCs** [jpanther/congo#389] [Q&A] [answered]
This is my `config/_default/config.toml`
``` toml
[params.utteranc]
repo = "XdpCs/xdpcs.github.io"
enable = true
issue-term = "title"
theme = "github-dark-orange"
```
But this is not work in my website.

**Comment by XdpCs** [comment]
I put this in `config/_default/params.toml`

``` toml
[utteranc]
repo = "XdpCs/xdpcs.github.io"
enable = true
issue-term = "title"
theme = "github-dark-orange"
```
this is also not work in my website.

**Reply by rshmhrj** [reply, marked as answer]
Hi @XdpCS , did you add a `comments.html` in your `layouts/partials`?

It should have something [like this](https://mscipio.github.io/post/utterances-comment-engine/) (hardcoded values are okay for testing):
```html
<script src="https://utteranc.es/client.js"
  repo="XdpCs/xdpcs.github.io"
  issue-term="title"
  label="Comment"
  theme="github-dark-orange"
  crossorigin="anonymous"
  async>
</script>
```

If that doesn't work, there are a few things to check to make sure comments display:
1. `config/_default/params.toml` > `[article]` > `showComments = true`: this will enable comments on all pages
2. if you want on only SOME pages, then set that `params.toml` value to false, and in the `.md` file you want to enable comments on, in the frontmatter at the top, add a new line with `showComments: true`

Deploying that should get the comments to display, and then if you want, you can un-hardcode:

`params.toml`:
```toml
[utterances]
repo = "XdpCs/xdpcs.github.io"
enabled = true
issueTerm = "title"
label = "Comment"
theme = "github-dark-orange"
```

`comments.html`:
```html
{{ if .Site.Params.utterances.enabled }}
<script src="https://utteranc.es/client.js"
  repo="{{ .Site.Params.utterances.repo }}"
  issue-term="{{ .Site.Params.utterances.issueTerm }}"
  label="{{ .Site.Params.utterances.label }}"
  theme="{{ .Site.Params.utterances.theme }}"
  crossorigin="anonymous"
  async>
</script>
{{ end }}
```

@jpanther maybe we could add a few sample `comments.html` examples in the docs to make starting with Disqus / Utteranc.es easier?
