### DISCUSSION TITLE
Twitter cards support

### DISCUSSION THREAD

**Discussion by Tanddant** [jpanther/congo#461] [Ideas]
When sharing posts to Twitter posts that have "Twitter Cards" generally gain more traction.

I've seen a few approaches to this, one is to set it up on a post by post level, or just one on the site as a whole.

But to begin with just a way to setup a Twittercard on all my pages would be awesome!

https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards

**Comment by Tanddant** [comment]
I'm a dum dum - this is built right into hugo

Added this to my 

   config\_default\config.toml


``` TOML
[params]
  description = 'Some description'
  images = ['img/TwitterCard.png']
 ```

And it looks to be working
