### DISCUSSION TITLE
Apply custom font

### DISCUSSION THREAD

**Discussion by bob3x255** [jpanther/congo#493] [Q&A]
Hi there! 

I am trying to add custom font from local source, however, it is not applied. Is there anything that I miss?

What I did so far:
1. Added font to `custom.css`
```
@font-face {
  font-family: 'custom-font';
  src: url('./assets/fonts/custom-font.ttf');
}
```
3. Extended tailwind config
```
    extend: {
      fontFamily: {
        'sans': ['custom-font', 'sans-serif']
      },
```
4. It seemed that `custom.css` is omitted after [building theme css from source](https://jpanther.github.io/congo/docs/advanced-customisation/#building-the-theme-css-from-source) and I added `      "./assets/css/custom.css` for `npm run build` command script.

Thanks!

**Comment by cosmicproc** [comment]
These worked for me:

**custom-font** path: `static/fonts/custom-font.woff2`

`custom.css`:
```css
@font-face {
    font-family: "custom-font";
    src: url("/fonts/custom-font.woff2") format("woff2");
}
```
`tailwind.config.js`:
```js
      ...
    extend: {
      ...
      fontFamily: {
        "sans": ["custom-font", "sans-serif"],
      },
      ...
```

You can also just use this if you don't want to build the theme css:

`custom.css`:
```css
@font-face {
    font-family: "custom-font";
    src: url("/fonts/custom-font.woff2") format("woff2");
}

html {
    font-family: custom-font, sans-serif;
}
```
