### DISCUSSION TITLE
Can't figure out how to set a custom color scheme

### DISCUSSION THREAD

**Discussion by AutonomousCat** [jpanther/congo#566] [Q&A]
I created `colorscheme.css` in assets/css/schemes/ and set the `colorScheme = "colorscheme"`.

I tested with green so it's very obvious and while it works to change the background color, text remains unaffected.

![image](https://github.com/jpanther/congo/assets/130127508/89ba08fd-12fc-4694-a310-9dc3156ed494)

_colorscheme.css_
```css
:root {
  --color-neutral: 25, 200, 25;
  --color-secondary: 25, 200, 25;
  --color-primary: 25, 200, 25;
}
```
The documentation over at https://jpanther.github.io/congo/docs/advanced-customisation/#colour-schemes feels misleading and vague. It points to the Tailwind site for palettes which exclusively uses hex codes, while also saying the color must be in r,g,b format. Beyond that, I don't understand what `-500` in the example means, but it didn't change anything with with that appended to `--color-neutral`. It also says each of neutral|secondary|primary contains 10 shades of color - how do I set those shades and how can I reduce it from 10 shades to 2 shades?
