### DISCUSSION TITLE
baseUrl, relUrl quirks in Netlify

### DISCUSSION THREAD

**Discussion by jacobleistra** [jpanther/congo#6] [Q&A] [answered]
I use Netlify for most of my CICD and hosting needs, and I'm running into an issue where no matter what the baseUrl is set to (e.g., "", "/", "www.something.com"), the relUrl of the menu links will point to the baseUrl and not the relative path of the content directory. This does not happen when serving locally.

The exact issue is pointed out here: https://answers.netlify.com/t/redirects-in-page-not-updating-url-correctly-when-deploying-from-github/13135. However, the fixes they propose have not been working for me. Unfortunately I'm not able to get it to work for my site. 

My live site in Netlify: https://www.chaosish.com/
The Treasure Haunt link in the menu should take me to: https://www.chaosish.com/treasurehaunt
The baseUrl in code is "/", and the pageRef in the menu.toml file is the name of the directory with the posts ("treasurehaunt").
Link to repo: https://github.com/jacobleistra/chaosish

Any idea why this is happening and how to get the relative path to work nicely in the menu?

**Comment by jpanther** [comment, marked as answer]
Thanks for the question. This seems strange to me because I use Netlify to deploy this theme on two separate sites. Part of the reasoning behind using relative URLs in the theme is to enable deployment to different hosts. What I'm doing for my own site is this:

```toml
# netlify.toml

[build]
  command = "hugo mod get -u && hugo --gc --minify -b $URL"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.87.0"
  HUGO_ENV = "production"
```

The `-b $URL` is setting the baseURL in Hugo to wherever Netlify is deploying to. Then in my Hugo `config.toml` I don't set any baseURL or other parameters that change the URL structure.
