### DISCUSSION TITLE
Is there an easy way to remove hover color on images?

### DISCUSSION THREAD

**Discussion by Aizera** [jpanther/congo#701] [Q&A] [answered]
I tried installing hugo-snap-gallery, when i click on the image once the entire thing shows the hover color of the link until i put my cursor at a corner. I understand that galleries are not supported but I thought it was worth an ask in case the fix is something I can quickly do on my end. Thanks!

https://aizera.page/post/atomic-habits-what-helped-me-the-most/

**Comment by wolfspyre** [comment]
I'm just guessing, but try adding this to the top of `custom.css` 

```css
@tailwind base;
@tailwind components; 
@tailwind utilities;

@layer base{
  html {
    /* https://css-tricks.com/custom-tailwind-css/ His recommendations */
    -webkit-tap-highlight-color: transparent;
    input, textarea, button, select, a {
      /* https://css-tricks.com/snippets/css/remove-gray-highlight-when-tapping-links-in-mobile-safari/ */
      -webkit-tap-highlight-color: transparent;
    }
  }  
}
```

and see if it helps?
