### DISCUSSION TITLE
Links with JavaScript URI scheme

### DISCUSSION THREAD

**Discussion by lneugebauer** [jpanther/congo#761] [Q&A]
Hi there,

I'd like to use JavaScript scheme in links as shown in the example below.

```toml
# config/_default/languages.en.toml

[author]
links = [
  { email = "javascript:linkTo_UnCryptMailto('acb');" }
]
```

Unfortunately the link gets rendered with url entities and doesn't work because of it.

```html
<a href="javascript:linkTo_UnCryptMailto%28%27acb%27%29;"><!-- icon --></a>
```

I see that links get rendered with [safeURL](https://gohugo.io/functions/safe/url/) which suggests that other schemes like `javascript:` should be supported.

Do you have any suggestions how to get this working?
