### DISCUSSION TITLE
Inline code backticks are shown, how to remove them

### DISCUSSION THREAD

**Discussion by dricard** [jpanther/congo#798] [Q&A] [answered]
When I use backticks to insert inline code in markdown I expect the rendered output _not_ to include the backticks but Congo shows them. Is there a way to remove them from the output?

For example this is an example of inline code using `qlmanage -p`:

![CleanShot 2024-01-29 at 10 05 17](https://github.com/jpanther/congo/assets/3743897/25c6f8f3-cf53-468f-937a-61dc0ff51184)

And this is what Congo does with `This is monospace font`:

![CleanShot 2024-01-29 at 10 05 42](https://github.com/jpanther/congo/assets/3743897/acd6bcb9-b516-4c66-92f8-fb28359ed803)

**Comment by dricard** [comment, marked as answer]
Answered my own question with a bit of digging into the css (posted for others who might want the same thing).

```css
.prose :where(code):not(:where([class~="not-prose"], [class~="not-prose"] *))::before {
    content: "";
}

.prose :where(code):not(:where([class~="not-prose"], [class~="not-prose"] *))::after {
    content: "";
}
```

Put that into custom.css.
