### DISCUSSION TITLE
List page not displaying correctly when deployed

### DISCUSSION THREAD

**Discussion by rshmhrj** [jpanther/congo#81] [Q&A] [answered]
## Question
Maybe I'm just doing things incorrectly as I'm new to Hugo.  This is the first time I turned a post to `draft: false` and it's not displaying on the list page, but it is showing up in tags and accessible via the URL.

Based on @jpanther's comments in #64, I had changed from a single `android-apps.md` file to the folder with the `index.md`

Don't know what else I'm missing and why the deployed "Posts" page doesn't seem to work correctly.  Does anything jump out at you all?

## Context
When I run `hugo server` and click "Posts" I see this:
![image](https://user-images.githubusercontent.com/750874/149634207-66201946-6ed4-4c03-8dcc-8997d4378b71.png)

When I run with draft mode on `hugo server -D` and click "Posts" I see this:
![image](https://user-images.githubusercontent.com/750874/149634231-c6d14c18-537f-4f3c-9956-c3c8f5b6c78d.png)

I have the site hosted on Gitlab Pages, and https://rshmhrj.io/posts/ is empty:
![image](https://user-images.githubusercontent.com/750874/149634249-8a4fd7c1-9f57-480b-8b3a-8c2f9bc43acc.png)

I can see the tag:
![image](https://user-images.githubusercontent.com/750874/149634342-fd34e88f-1569-4ee7-8dae-e5dd4a7bc20d.png)

and can hit the page, https://rshmhrj.io/posts/android-apps/:
![image](https://user-images.githubusercontent.com/750874/149634360-02fc0129-1bb9-45eb-b755-ea03f8b88741.png)

Here's the `content/posts` files.
```bash
.
├── android-apps
│   ├── index.md
│   ├── play-store-pics
│   │   ├── callu-app.png
│   │   ├── flipp-app.png
│   │   ├── guitar-tuna-app.png
│   │   ├── mr-number-app.png
│   │   └── snore-lab-app.png
│   └── screenshots
│       ├── Screenshot_20220114-231703_One_UI_Home.jpg
│       ├── Screenshot_20220114-231718_Maps.jpg
│       ├── Screenshot_20220114-231737_Maps.jpg
│       └── Screenshot_20220114-231816_One_UI_Home.jpg
├── cli-tools.md
├── first.md
├── macos-apps.md
├── windows-apps.md
└── xplatform-apps.md
```

**Comment by jpanther** [comment, marked as answer]
This is strange behaviour and at a glance I'm not sure what would be causing this. What is the command that you're using to build and deploy on Gitlab? The folder structure you're using is exactly how the example site works and so that shouldn't be a problem.

**Reply by rshmhrj** [reply]
Here are the contents of the `.gitlab-ci.yaml` file:
```yaml
# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
```

Originally I had downloaded the `congo` theme and copied the files manually.  Yesterday, I updated it to the git submodule method:
```bash
git rm -r themes/congo
git submodule add -b stable https://github.com/jpanther/congo.git themes/congo
```

The CI file already had `recursive` set for submodules, so it seemed like it deployed fine -- it's just that list page doesn't seem to work.  Outside of `hugo server` / `hugo server -D`, I'm not aware of any other ways to test and validate that things are working.  Side question: do you know if there are ways to do unit / integration testing of themes and sites built on top of them?

**Reply by rshmhrj** [reply]
Welp, this is weird...fixed it but not sure why it worked -- maybe you could help me understand what the problem was.

The fix was removing the `post="posts"` line in the `taxonomies.toml` file:

```toml
tag="tags"
category="categories"
topic="topics"
about="about"
project="projects"
post="posts"
```

I was under the impression that taxonomies were just a way of grouping content, but it seems that having a taxonomy which matches a top level folder doesn't seem to deploy properly (at least on Gitlab Pages).  I don't understand why that would be the case though, but removing it worked: https://rshmhrj.io/posts/
