### DISCUSSION TITLE
Would you accept a PR for Umami Analytics ?

### DISCUSSION THREAD

**Discussion by fmaida** [jpanther/congo#829] [Ideas]
Would you accept a Pull request that adds Umami Analytics support to the theme?

My idea is about adding this parameter to the `config/_default/params.toml` file:

```toml
[umamiAnalytics]
    site = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX"
    region = "eu"  # Accepted values: "eu" or "us"
```

And use it in the `layouts/partials/analytics.html` file:

```html
{{ with .Site.Params.umamiAnalytics }}
    <script defer 
        src="https://{{ .region | "eu" }.umami.is/script.js" 
        data-website-id="{{ .site }}">
    </script>
{{ end }}
```
