### DISCUSSION TITLE
Is there a way to translate the title of the posts page?

### DISCUSSION THREAD

**Discussion by bugok** [jpanther/congo#855] [Q&A] [answered]
I'm currently starting to experiment with the theme, using a single language, Hebrew. It's pleasantly surprising how well this is working out of the box. 

One thing which I wasn't able to figure out is how to translate the title of the Posts page. The title is `Posts` and not the Hebrew translation. 

Is there a way to do that? Or perhaps override that specific title?

I'd be happy send a PR given some hints and pointers. 

Thanks!

EDIT: Here's where the title is set: https://github.com/jpanther/congo/blob/stable/layouts/_default/list.html#L7

**Comment by wolfspyre** [comment]
my guess would be it being the name of the taxonomy?

**Comment by bugok** [comment, marked as answer]
I found it, and it was in the documentation as well... Shame on me for not searching properly. 

As it says here: https://jpanther.github.io/congo/docs/content-examples/#list-pages

I needed to create a `posts/_index.md` file and there I could override the title as well. 

For example:
`content/posts/_index.md`:

```
---
title: "פוסטים"
description: "הפוסטים שיש באתר"

cascade:
  showEdit: false
  showSummary: true
  showDate: true
  showReadingTime: true
---
```

This worked for me :)
