### DISCUSSION TITLE
GitHub Actions -> Failing on my recent post, but most of content is the same, no new features.

### DISCUSSION THREAD

**Discussion by jvanderaa** [jpanther/congo#882] [Q&A] [answered]
I've been doing a bit of troubleshooting, but coming up empty at this point. At the moment I'm trying to revert back to 2.7.4 version. But wanted to get the error here and if anyone has any suggestions of what may be causing this? 

```
"/tmp/hugo_cache_runner/modules/filecache/modules/pkg/mod/github.com/jpanther/congo/v2@v2.8.2/layouts/index.html:4:7": execute of template failed: template: index.html:4:7: executing "main" at <partial $partial .>: error calling partial: partial "partials/home/profile.html" timed out after 30s. This is most likely due to infinite recursion. If this is just a slow template, you can try to increase the 'timeout' config setting.
```

Primary update was to `config/_default/languages.en.toml`. This started with a new PR. I'm going to work to take one step at a time to first get the new post out that I am looking to do, then migrate to 2.8.2 again. I think what was missing in my last attempt is I didn't publish any new posts.

**Comment by jvanderaa** [comment]
The interesting thing is that the build locally on the system works just fine. It's only in the GitHub Pages CI workflow.

```yaml
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
          TZ: America/Chicago
        run: |
          hugo \
            --gc \
            --minify \
            --debug \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
```
