### DISCUSSION TITLE
On small (phone) screens, could we have an option to move a page's table of contents to a second, separate hamburger menu?

### DISCUSSION THREAD

**Discussion by venteto** [jpanther/congo#904] [Ideas]
I have some pages with very long tables of contents, and when I preview them at typical phone screen sizes, it's a long way down before you see any actual content. And honestly, I don't really even know what the actual best UX is for a case like this, I hate that browsing the web on little phones is even a thing, because the ToC looks soooooooo much nicer on a laptop screen, it's a pity to turn off ToC generation just because someone might look at the page on a phone.

Or perhaps there could be separate configuration settings to independently enable/disable ToC generation (globally) on both small and normal screens ... maybe something like:
```toml
tableOfContentsLayout = "hybrid" # valid options: , basic, hamburger, hybrid, custom
showTableOfContents = true
showTableOfContentsSmallScreen = false
```

![Screenshot from 2024-06-27 09-22-21](https://github.com/jpanther/congo/assets/7062385/9548f4b5-7ecc-4b73-a7dc-33a9f2d1ca15)
