### ISSUE TITLE
Parameter 'mainSections' is language dependent

### ISSUE THREAD

**Issue by metbril** [jpanther/congo#376]
### What happened?

I have a bilingual site (nl and en) and have `mainSections = "['posts']"` in my `params.toml`. However, this setting is only working for the main language. When I add a section to my `languages.en.toml` file, it is working just fine.

The documentation should be updated to reflect this. Since it is in multiple files, I can't provide a quick PR. But the workaround is, to remove the parameter from the params file and move it to all occurrences of the languages config.

**config/_default/languages.nl.toml**
```toml
[params]
  mainSections = [ "posts" ]
```

**config/_default/languages.en.toml**
```toml
[params]
  mainSections = [ "posts" ]
```

### Theme version

latest

### Hugo version

latest
