### ISSUE TITLE
utteranc don't  work

### ISSUE THREAD

**Issue by XdpCs** [jpanther/congo#390]
### Discussed in https://github.com/jpanther/congo/discussions/389

<div type='discussions-op-text'>

<sup>Originally posted by **XdpCS** November 27, 2022</sup>
This is my `config/_default/config.toml`
``` toml
[params.utteranc]
repo = "XdpCs/xdpcs.github.io"
enable = true
issue-term = "title"
theme = "github-dark-orange"
```
But this is not work in my website.</div>

**Comment by XdpCs** [comment]
I put this in `config/_default/params.toml`
``` toml
[utteranc]
repo = "XdpCs/xdpcs.github.io"
enable = true
issue-term = "title"
theme = "github-dark-orange"
```
this is also not work in my website.
