### ISSUE TITLE
`logoDark` & `logo` parameters reversed in hybrid header layout with `defaultAppearance` set to "dark"

### ISSUE THREAD

**Issue by socrabytes** [jpanther/congo#939]
### Issue description

In config file `params.toml`, the `header.logo` and `header.logoDark` parameters seem to be swapped. The dark mode logo appears in light mode and vice versa. The only customization I’ve made is setting `defaultAppearance = "dark"` instead of the default "light", which might be related to the issue. Otherwise, no significant customizations come to mind.

```toml
defaultAppearance = "dark" 
autoSwitchAppearance = true

[header]
  layout = "hybrid" 
  logo = "img/logo-dark.png" # Bug: theme improperly handling logo versions of light/dark
  logoDark = "img/logo.png" 
```
This is a minor issue, but I thought it would be helpful to report it. Thank you for providing this theme and for all the effort you’ve put into maintaining it!

  

### Theme version

v2.9.0

### Hugo version

hugo v0.134.3+extended linux/amd64

### Which browser rendering engines are you seeing the problem on?

Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, Opera, etc.)

### URL to sample repository or website

https://github.com/socrabytes/socrabytes.github.io

### Hugo output or build error messages

```bash
N/A
```
