### ISSUE TITLE
Author parameters not rendering at posts

### ISSUE THREAD

**Issue by DarkPro1337** [jpanther/congo#96]
### What happened?

I'm just started using Congo, but something went wrong with rendering author parameters on posts pages. That's very frustrating. I'm already tried to downgrade theme version, switched from `extended` to default Hugo version, reverified `.toml` files. 

Nothing helps. Parameters are just ignored and author blocks and other parameters not rendering.

That's how posts rendering for me.
![image](https://user-images.githubusercontent.com/19241806/151795993-51519a82-e9a0-4406-9bd8-a33b0ca28e0c.png)

As you can see author block not rendered, and even breadcrumbs. Sharing and edit button too not visible.

```toml
# config/_default/config.toml
baseURL = "https://darkpro1337.github.io/"
languageCode = "en"
defaultContentLanguage = "en"
publishDir = "../darkpro1337.github.io"

title = "DarkPro1337"

enableEmoji = true
enableRobotsTXT = true

summaryLength = 0

[author]
  name = "Artem Darkov"
  image = "img/author.jpg"
  bio = "21 y.o. C# Developer"
  links = [
    # links
  ]

# config/_default/params.toml
[article]
  showDate = true
  dateFormat = "2 January 2006"
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = true
  editURL = "https://github.com/DarkPro1337/main/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showWordCount = false
  sharingLinks = ["facebook", "twitter", "pinterest", "reddit", "linkedin", "email"]
```
Full source available [here](https://github.com/DarkPro1337/main)

### Theme version

v1.6.4

### Hugo version

v0.92.1

### What browsers are you seeing the problem on?

Microsoft Edge
